apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat

  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: DOCKERUSER/IMAGENAME:BUILDNUMBER
        ports:
        - name: tomcatport
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
spec:
  ports:
  - port: 8888
    nodePort: 31002
    targetPort: tomcatport
    protocol: TCP
  selector:
    app: tomcat
  type: NodePort
